In [579]:
import pandas as pd

In [580]:
df = pd.read_csv('african_crises.csv')
df

case  cc3   country  year  systemic_crisis    exch_usd  \
0        1  DZA   Algeria  1870                1    0.052264   
1        1  DZA   Algeria  1871                0    0.052798   
2        1  DZA   Algeria  1872                0    0.052274   
3        1  DZA   Algeria  1873                0    0.051680   
4        1  DZA   Algeria  1874                0    0.051308   
...    ...  ...       ...   ...              ...         ...   
1054    70  ZWE  Zimbabwe  2009                1  354.800000   
1055    70  ZWE  Zimbabwe  2010                0  378.200000   
1056    70  ZWE  Zimbabwe  2011                0  361.900000   
1057    70  ZWE  Zimbabwe  2012                0  361.900000   
1058    70  ZWE  Zimbabwe  2013                0  361.900000   

      domestic_debt_in_default  sovereign_external_debt_default  \
0                            0                                0   
1                            0                                0   
2                            0                                0   
3                            0                                0   
4                            0                                0   
...                        ...                              ...   
1054                         1                                1   
1055                         1                                1   
1056                         1                                1   
1057                         1                                1   
1058                         1                                1   

      gdp_weighted_default  inflation_annual_cpi  independence  \
0                      0.0              3.441456             0   
1                      0.0             14.149140             0   
2                      0.0             -3.718593             0   
3                      0.0             11.203897             0   
4                      0.0             -3.848561             0   
...                    ...                   ...           ...   
1054                   0.0             -7.670000             1   
1055                   0.0              3.217000             1   
1056                   0.0              4.920000             1   
1057                   0.0              3.720000             1   
1058                   0.0              1.632000             1   

      currency_crises  inflation_crises banking_crisis  
0                   0                 0         crisis  
1                   0                 0      no_crisis  
2                   0                 0      no_crisis  
3                   0                 0      no_crisis  
4                   0                 0      no_crisis  
...               ...               ...            ...  
1054                1                 0         crisis  
1055                0                 0      no_crisis  
1056                0                 0      no_crisis  
1057                0                 0      no_crisis  
1058                0                 0      no_crisis  

[1059 rows x 14 columns]

In [581]:
df.info() #пропусков нет

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   case                             1059 non-null   int64  
 1   cc3                              1059 non-null   object 
 2   country                          1059 non-null   object 
 3   year                             1059 non-null   int64  
 4   systemic_crisis                  1059 non-null   int64  
 5   exch_usd                         1059 non-null   float64
 6   domestic_debt_in_default         1059 non-null   int64  
 7   sovereign_external_debt_default  1059 non-null   int64  
 8   gdp_weighted_default             1059 non-null   float64
 9   inflation_annual_cpi             1059 non-null   float64
 10  independence                     1059 non-null   int64  
 11  currency_crises                  1059 non-null   int64  
 12  inflation_crises    

In [582]:
sum(df.duplicated()) #дублированных нет

0

In [583]:
df.describe()

case         year  systemic_crisis     exch_usd  \
count  1059.000000  1059.000000      1059.000000  1059.000000   
mean     35.613787  1967.767705         0.077432    43.140831   
std      23.692402    33.530632         0.267401   111.475380   
min       1.000000  1860.000000         0.000000     0.000000   
25%      15.000000  1951.000000         0.000000     0.195350   
50%      38.000000  1973.000000         0.000000     0.868400   
75%      56.000000  1994.000000         0.000000     8.462750   
max      70.000000  2014.000000         1.000000   744.306139   

       domestic_debt_in_default  sovereign_external_debt_default  \
count               1059.000000                      1059.000000   
mean                   0.039660                         0.152975   
std                    0.195251                         0.360133   
min                    0.000000                         0.000000   
25%                    0.000000                         0.000000   
50%                    0.000000                         0.000000   
75%                    0.000000                         0.000000   
max                    1.000000                         1.000000   

       gdp_weighted_default  inflation_annual_cpi  independence  \
count           1059.000000          1.059000e+03   1059.000000   
mean               0.006402          2.084889e+04      0.776204   
std                0.043572          6.757274e+05      0.416984   
min                0.000000         -2.850214e+01      0.000000   
25%                0.000000          2.086162e+00      1.000000   
50%                0.000000          5.762330e+00      1.000000   
75%                0.000000          1.164405e+01      1.000000   
max                0.400000          2.198970e+07      1.000000   

       currency_crises  inflation_crises  
count      1059.000000       1059.000000  
mean          0.132200          0.129367  
std           0.349847          0.335765  
min           0.000000          0.000000  
25%           0.000000          0.000000  
50%           0.000000          0.000000  
75%           0.000000          0.000000  
max           2.000000          1.000000

In [584]:
#сделаем так, чтобы последний столбец, как и все, показывал наличие кризиса единицами или нулями.

def rephorm(x):
    if x == "no_crisis":
        return 0
    elif x == "crisis":
        return 1
    
df["banking_crisis"] = df["banking_crisis"].apply(rephorm)
df

case  cc3   country  year  systemic_crisis    exch_usd  \
0        1  DZA   Algeria  1870                1    0.052264   
1        1  DZA   Algeria  1871                0    0.052798   
2        1  DZA   Algeria  1872                0    0.052274   
3        1  DZA   Algeria  1873                0    0.051680   
4        1  DZA   Algeria  1874                0    0.051308   
...    ...  ...       ...   ...              ...         ...   
1054    70  ZWE  Zimbabwe  2009                1  354.800000   
1055    70  ZWE  Zimbabwe  2010                0  378.200000   
1056    70  ZWE  Zimbabwe  2011                0  361.900000   
1057    70  ZWE  Zimbabwe  2012                0  361.900000   
1058    70  ZWE  Zimbabwe  2013                0  361.900000   

      domestic_debt_in_default  sovereign_external_debt_default  \
0                            0                                0   
1                            0                                0   
2                            0                                0   
3                            0                                0   
4                            0                                0   
...                        ...                              ...   
1054                         1                                1   
1055                         1                                1   
1056                         1                                1   
1057                         1                                1   
1058                         1                                1   

      gdp_weighted_default  inflation_annual_cpi  independence  \
0                      0.0              3.441456             0   
1                      0.0             14.149140             0   
2                      0.0             -3.718593             0   
3                      0.0             11.203897             0   
4                      0.0             -3.848561             0   
...                    ...                   ...           ...   
1054                   0.0             -7.670000             1   
1055                   0.0              3.217000             1   
1056                   0.0              4.920000             1   
1057                   0.0              3.720000             1   
1058                   0.0              1.632000             1   

      currency_crises  inflation_crises  banking_crisis  
0                   0                 0               1  
1                   0                 0               0  
2                   0                 0               0  
3                   0                 0               0  
4                   0                 0               0  
...               ...               ...             ...  
1054                1                 0               1  
1055                0                 0               0  
1056                0                 0               0  
1057                0                 0               0  
1058                0                 0               0  

[1059 rows x 14 columns]

В какой африканской стране кризисы происходят чаще?

In [585]:
#новый столбец с инфой о количестве кризисов в году
df["namber_oph_kraizises"] = df["systemic_crisis"] + df["currency_crises"] + df["inflation_crises"] + df["banking_crisis"]

In [591]:
kraizises = {} 
years = {}

for i in range(1059):
    if i != 1058 and df["country"].iloc[i] == df["country"].iloc[i+1]:
        cur_cr += df["namber_oph_kraizises"].iloc[i]  
        year+=1
    if (i == 1058) or (df["country"].iloc[i] != df["country"].iloc[i+1]):
        cur_cr += df["namber_oph_kraizises"].iloc[i]   
        year += 1
        kraizises[df["country"].iloc[i]] = cur_cr
        years[df["country"].iloc[i]] = year
        cur_cr = 0
        year = 0

kraizises

{'Algeria': 31,
 'Angola': 55,
 'Central African Republic': 42,
 'Ivory Coast': 13,
 'Egypt': 36,
 'Kenya': 34,
 'Mauritius': 12,
 'Morocco': 22,
 'Nigeria': 43,
 'South Africa': 20,
 'Tunisia': 28,
 'Zambia': 47,
 'Zimbabwe': 70}

In [511]:
years

{'Algeria': 85,
 'Angola': 77,
 'Central African Republic': 58,
 'Ivory Coast': 63,
 'Egypt': 155,
 'Kenya': 67,
 'Mauritius': 68,
 'Morocco': 75,
 'Nigeria': 60,
 'South Africa': 114,
 'Tunisia': 75,
 'Zambia': 72,
 'Zimbabwe': 90}

In [512]:
znachenie = {}
for country in kraizises:
    znachenie[country] = kraizises[country] / years[country]

znachenie

{'Algeria': 0.36470588235294116,
 'Angola': 0.7142857142857143,
 'Central African Republic': 0.7241379310344828,
 'Ivory Coast': 0.20634920634920634,
 'Egypt': 0.23225806451612904,
 'Kenya': 0.5074626865671642,
 'Mauritius': 0.17647058823529413,
 'Morocco': 0.29333333333333333,
 'Nigeria': 0.7166666666666667,
 'South Africa': 0.17543859649122806,
 'Tunisia': 0.37333333333333335,
 'Zambia': 0.6527777777777778,
 'Zimbabwe': 0.7777777777777778}

In [513]:
#Чаще всего кризисы происходят в... *барабанная дробь*
max(znachenie)

'Zimbabwe'

Ответ: Зимбабве

Как связаны кризисы и независимость африканского государства?

In [571]:
#надо знать величины для построения таблицы
max(df["namber_oph_kraizises"])

dft = df.drop(['year', 'case', 'cc3', 'country', 'systemic_crisis', 'exch_usd', 'domestic_debt_in_default', 'sovereign_external_debt_default', 'gdp_weighted_default', 'inflation_annual_cpi', 'currency_crises', 'inflation_crises', 'banking_crisis'], axis=1)

dft

independence  namber_oph_kraizises
0                0                     2
1                0                     0
2                0                     0
3                0                     0
4                0                     0
...            ...                   ...
1054             1                     3
1055             1                     0
1056             1                     0
1057             1                     0
1058             1                     0

[1059 rows x 2 columns]

In [575]:
dft.corr()

independence  namber_oph_kraizises
independence              1.000000              0.124821
namber_oph_kraizises      0.124821              1.000000

#### Модель для предсказаний

In [514]:
zam = df[df["country"] == "Zambia"]


zam

case  cc3 country  year  systemic_crisis  exch_usd  \
897    69  ZMB  Zambia  1943                0  0.000498   
898    69  ZMB  Zambia  1944                0  0.000498   
899    69  ZMB  Zambia  1945                0  0.000497   
900    69  ZMB  Zambia  1946                0  0.000497   
901    69  ZMB  Zambia  1947                0  0.000496   
..    ...  ...     ...   ...              ...       ...   
964    69  ZMB  Zambia  2010                0  4.789900   
965    69  ZMB  Zambia  2011                0  5.113980   
966    69  ZMB  Zambia  2012                0  5.146613   
967    69  ZMB  Zambia  2013                0  5.520000   
968    69  ZMB  Zambia  2014                0  6.385600   

     domestic_debt_in_default  sovereign_external_debt_default  \
897                         0                                0   
898                         0                                0   
899                         0                                0   
900                         0                                0   
901                         0                                0   
..                        ...                              ...   
964                         0                                0   
965                         0                                0   
966                         0                                0   
967                         0                                0   
968                         0                                0   

     gdp_weighted_default  inflation_annual_cpi  independence  \
897                   0.0              2.857143             0   
898                   0.0              2.777778             0   
899                   0.0              2.702703             0   
900                   0.0              7.894737             0   
901                   0.0              2.439024             0   
..                    ...                   ...           ...   
964                   0.0              8.500000             1   
965                   0.0              8.658000             1   
966                   0.0              6.575000             1   
967                   0.0              6.978000             1   
968                   0.0              7.811000             1   

     currency_crises  inflation_crises  banking_crisis  namber_oph_kraizises  
897                0                 0               0                     0  
898                0                 0               0                     0  
899                0                 0               0                     0  
900                0                 0               0                     0  
901                0                 0               0                     0  
..               ...               ...             ...                   ...  
964                0                 0               0                     0  
965                0                 0               0                     0  
966                0                 0               0                     0  
967                1                 0               0                     1  
968                0                 0               0                     0  

[72 rows x 15 columns]

In [518]:
#сделаем массив с валютным кризисом
array1 = zam['currency_crises'].values
array1

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0], dtype=int64)

In [535]:
n = 0
M = []
while n != array1.shape[0]-3:
    M.append(array1[n+3])
    n += 1

In [536]:
M = np.array(M)
M

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0], dtype=int64)

In [521]:
#массив для стоимости валюты
array2 = zam['exch_usd'].values

In [522]:
for i in range(len(array2)):
    array2[i] = float(array2[i])
array2 = array2/100

In [523]:
i = 0
X = []
while i != array2.shape[0]-3:
    X.append(array2[i:i+3])
    i += 1

In [525]:
X = np.stack(X)
X

array([[4.9760000e-06, 4.9760000e-06, 4.9680000e-06],
       [4.9760000e-06, 4.9680000e-06, 4.9680000e-06],
       [4.9680000e-06, 4.9680000e-06, 4.9580000e-06],
       [4.9680000e-06, 4.9580000e-06, 4.9600000e-06],
       [4.9580000e-06, 4.9600000e-06, 7.1420000e-06],
       [4.9600000e-06, 7.1420000e-06, 7.1400000e-06],
       [7.1420000e-06, 7.1400000e-06, 7.1900000e-06],
       [7.1400000e-06, 7.1900000e-06, 7.1180000e-06],
       [7.1900000e-06, 7.1180000e-06, 7.1160000e-06],
       [7.1180000e-06, 7.1160000e-06, 7.1800000e-06],
       [7.1160000e-06, 7.1800000e-06, 7.1360000e-06],
       [7.1800000e-06, 7.1360000e-06, 7.1800000e-06],
       [7.1360000e-06, 7.1800000e-06, 7.1200000e-06],
       [7.1800000e-06, 7.1200000e-06, 7.1380000e-06],
       [7.1200000e-06, 7.1380000e-06, 7.1440000e-06],
       [7.1380000e-06, 7.1440000e-06, 7.1340000e-06],
       [7.1440000e-06, 7.1340000e-06, 7.1220000e-06],
       [7.1340000e-06, 7.1220000e-06, 7.1360000e-06],
       [7.1220000e-06, 7.136

In [526]:
#Делаем модель
xtrain, xtest, mtrain, mtest = train_test_split(X, M)


In [527]:
# к делу приступает линейная регрессия
lr = LinearRegression()

In [528]:
lr.fit(xtrain, mtrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [540]:
#чекаем ошибки
print('среднеквадратичная ошибка =', mean_squared_error(mtest, lr.predict(xtest)), '; '
      'абсолютная ошибка =', mean_absolute_error(mtest, lr.predict(xtest)))

среднеквадратичная ошибка = 0.2448513201394135 ; абсолютная ошибка = 0.4102486867821721


In [541]:
X[-1]

array([0.0511398 , 0.05146613, 0.0552    ])

In [542]:
M[-1]

0

In [544]:
#предскажем
lr.predict([X[-1]])

array([0.1125804])